---
title: "Lab3"
author: "Taylor Wise"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tasks

## Task 1
Get working directory
```{r}
getwd()
```

## Task 2
Reading in the file and show the first 6 lines of data
```{r}
spruce <- read.csv("SPRUCE.csv")
head(spruce)
```

## Task 3
<!--
use cex=1.2
-->

```{r}
with(spruce, plot(BHDiameter, Height, pch=21, bg="Blue", main = "Scatter Plot of Height vs BHDiameter", cex=1.2), xlim=c(0,1.1 * max_x), ylim = c(0, 1.1 * max_y))
```

There does not appear to be a straight line relationship based on the graph above
<!--
spruce$Height, spruce$BHDiameter can also be used in trendscatter
-->

```{r}
library(s20x)

layout(matrix(1:3, nrow=1, byrow=TRUE))

trendscatter(Height~BHDiameter, data=spruce, f=0.5)

trendscatter(Height~BHDiameter, data=spruce, f=0.6)

trendscatter(Height~BHDiameter, data=spruce, f=0.7)
```

```{r}
spruce.lm <- lm(Height~BHDiameter, data = spruce)

with(spruce, plot(BHDiameter, Height, pch=21, bg="Blue", main = "Scatter Plot of Height vs BHDiameter", cex=1.2), xlim=c(0,1.1 * max_x), ylim = c(0, 1.1 * max_y))

abline(spruce.lm)
```

## Task 4
```{r}
lo = layout(matrix(1:4, nr = 2,  nc = 2, byrow = TRUE))

# First square
with(spruce, plot(BHDiameter, Height, pch=21, bg="Blue", main = "Scatter Plot of Height vs BHDiameter", cex=1.2), xlim=c(0,1.1 * max_x), ylim = c(0, 1.1 * max_y))

spruce.lm <- lm(Height~BHDiameter, data = spruce)
abline(spruce.lm)

# Second square

with(spruce, plot(BHDiameter, Height, pch=21, bg="Blue", main = "Scatter Plot of Height vs BHDiameter", cex=1.2), xlim=c(0,1.1 * max_x), ylim = c(0, 1.1 * max_y))
abline(spruce.lm)

deviations <- with(spruce, predict(spruce.lm, data.frame(BHDiameter)))

with(spruce, {segments(BHDiameter, Height, BHDiameter, deviations)})
abline(spruce.lm)

RSS <- with(spruce, sum((Height-deviations)^2))
print(RSS)

# Third square

with(spruce, plot(BHDiameter, Height, pch=21, bg="Blue", main = "Scatter Plot of Height vs BHDiameter", cex=1.2), xlim=c(0,1.1 * max_x), ylim = c(0, 1.1 * max_y))

with(spruce, abline(h=mean(Height)))
abline(spruce.lm)

with(spruce, segments(BHDiameter, mean(Height), BHDiameter, deviations, col="Red"))

MSS <- with(spruce, sum((deviations-mean(Height))^2))
print(MSS)

# Fourth square

with(spruce, plot(BHDiameter, Height, pch=21, bg="Blue", main = "Scatter Plot of Height vs BHDiameter", cex=1.2), xlim=c(0,1.1 * max_x), ylim = c(0, 1.1 * max_y))

with(spruce, abline(h=mean(Height)))
with(spruce, segments(BHDiameter, Height, BHDiameter, mean(Height), col="Green"))

TSS <- with(spruce, sum((Height-mean(Height))^2))
print(TSS)
  
# Calculations

print(MSS/TSS)

print(MSS+RSS)
```


## Task 5
```{r}
summary(spruce.lm)
```

```{r}
predict(spruce.lm, data.frame(BHDiameter = c(15, 18, 20)))
```

## Task 6
```{r}
library(ggplot2)

g <- ggplot(spruce, aes(x = BHDiameter, y = Height, colour = BHDiameter))
g <- g + geom_point() + geom_line() + geom_smooth(method = "lm")
g
```


## Task 7
