---
title: "Lab5"
author: "Taylor Wise"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tasks

## Task 1

### Get Working Directory
```{r}
getwd()
```

## Task 2

### mybin
```{r}
mybin=function(iter=100, n=10, p=0.5){
  sam.mat=matrix(NA,nr=n,nc=iter, byrow=TRUE)
  
  succ=c()
  for( i in 1:iter){
    sam.mat[,i]=sample(c(1,0),n,replace=TRUE, prob=c(p,1-p))

    succ[i]=sum(sam.mat[,i])
  }

succ.tab=table(factor(succ,levels=0:n))
succ.tab

barplot(succ.tab/(iter), col=rainbow(n+1), main="Binomial simulation", xlab="Number of successes")
succ.tab/iter
}
```

### n=10, p=0.7
```{r}
mybin(n=10, p=0.7)
```

### iter=100, n=10, p=0.7
```{r}
mybin(iter=100, n=10, p=0.7)
```

### iter=200, n=10, p=0.7
```{r}
mybin(iter=200, n=10, p=0.7)
```

### iter=500, n=10, p=0.7
```{r}
mybin(iter=500, n=10, p=0.7)
```

### iter=1000, n=10, p=0.7
```{r}
mybin(iter=1000, n=10, p=0.7)
```

### iter=10000, n=10, p=0.7
```{r}
mybin(iter=10000, n=10, p=0.7)
```

### iter=10000 table
```{r}
BinTenThousTable <- mybin(iter=10000, n=10, p=0.7)
BinTenThousTable
```

### verify with dbinom
```{r}
dbinom(1:10, 10, 0.7)
```

## Task 3

### without replacement
```{r}
sample(c(1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0), 5, replace=FALSE)
```

### with replacement
```{r}
sample(c(1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0), 5, replace=TRUE)
```

### myhyper
```{r}
myhyper=function(iter=100, n=5, r=12, N=20){
  sam.mat=matrix(NA,nr=n,nc=iter, byrow=TRUE)
  
  succ=c()
  for( i in 1:iter){
    sam.mat[,i]=sample(rep(c(1,0),c(r,N-r)),n,replace=FALSE)

    succ[i]=sum(sam.mat[,i])
  }

succ.tab=table(factor(succ,levels=0:n))
succ.tab

barplot(succ.tab/(iter), col=rainbow(n+1), main="Hyper simulation", xlab="Number of successes")
succ.tab/iter
}
```

### iter=100, n=5, r=12, N=20
```{r}
myhyper(iter=100, n=5, r=12, N=20)
```

### iter=200, n=5, r=12, N=20
```{r}
myhyper(iter=200, n=5, r=12, N=20)
```

### iter=500, n=5, r=12, N=20
```{r}
myhyper(iter=500, n=5, r=12, N=20)
```

### iter=1000, n=5, r=12, N=20
```{r}
myhyper(iter=1000, n=5, r=12, N=20)
```

### iter=10000, n=5, r=12, N=20
```{r}
myhyper(iter=10000, n=5, r=12, N=20)
```

### iter=10000 table
```{r}
HyperTenThousTable <- myhyper(iter=10000, n=5, r=12, N=20)
HyperTenThousTable
```

### dhyper
```{r}
dhyper(0:5, 12, 8, 5)
```

## Task 4
### mysample
```{r}
mysample=function(n, iter=10,time=0.5){
  for( i in 1:iter){
  
      s=sample(1:10,n,replace=TRUE)
      
      sf=factor(s,levels=1:10)
      
      barplot(table(sf)/n,beside=TRUE,col=rainbow(10), 
      main=paste("Example sample()", " iteration ", i, " n= ", n,sep="") ,
      ylim=c(0,0.2)
      )
      
      Sys.sleep(time)
  }
}

# mysample(n=1000, time=1, iter=30)
# Says we only need one of the 30 iterations so will be using one interation so will be using iter=1 version of above commented code
mysample(n=1000, time=1, iter=1)
```

## Task 5
```{r}
choose(8,4)
```

```{r}
dpois(4,2)
```

```{r}
#Check
dnbinom(10,3,0.4)
```

```{r}
pbinom(8,15,0.4)
```

## Task 6
```{r}
library(SPRING244753wise0054)
rm("mybinny")
SPRING244753wise0054::mybinny(100,10,0.7)
```

